### ISSUE TITLE
Will a beautiful homepage 

### ISSUE THREAD

**Issue by BxtGeek** [abhinavkashyap061/todolist#5]

**Comment by anushkamandal25** [comment]
Hello! Is this issue applicable for hacktoberfest? This is my first time in hacktoberfest. I want to contribute in this issue. So please assign me.

**Comment by abhinavkashyap061** [comment]
Hey @BxtGeek  👋, Thanks for considering contributing to my project

Can you please tell the details of that homepage.

Happy Hacking 🚀

**Comment by abhinavkashyap061** [comment]
Hey @anushkamandal25 👋, Thanks for considering contributing to my project

Yes, the contribution to this repo will be applicable for Hacktoberfest. Please tell the details/improvements that you will make in current homepage so that it counts as a valuable contribution and I will assign you.

Happy Hacking 🚀

**Comment by Kritika30032002** [comment]
Hey!! 

Is this still available?
Can I contribute to this? If yes, then you can assign this to me!!
